version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - treetagger_data:/treetagger  # Persistent TreeTagger data
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

volumes:
  treetagger_data:

