version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - TAGDIR=/app/treetagger  # This should be set correctly
    restart: unless-stopped

