version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/treetagger
    environment:
    - TAGDIR=/app/treetagger/TreeTagger
    restart: unless-stopped

